// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbit_BE.Data;

#nullable disable

namespace Orbit_BE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260219141720_InitialCreate_Postgres")]
    partial class InitialCreate_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbit_BE.Entities.CanvasEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_node_id");

                    b.Property<DateTime?>("LastEditedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_timestamp");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_state");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_node_id");

                    b.HasKey("Id")
                        .HasName("pk_canvas_edges");

                    b.HasIndex("FromNodeId")
                        .HasDatabaseName("ix_canvas_edges_from_node_id");

                    b.HasIndex("ToNodeId")
                        .HasDatabaseName("ix_canvas_edges_to_node_id");

                    b.ToTable("canvas_edges", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BasePath")
                        .HasColumnType("text")
                        .HasColumnName("base_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastEditedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_state");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_provider");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_nodes_parent_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_nodes_user_id");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.NodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<DateTime?>("LastEditedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_timestamp");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_state");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_node_files");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_files_node_id");

                    b.ToTable("node_files", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.NodePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastEditedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_timestamp");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_state");

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_node_positions");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_positions_node_id");

                    b.ToTable("node_positions", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway_name");

                    b.Property<long>("PurchasedStorageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("purchased_storage_mb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastEditedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_timestamp");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("RecordState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_state");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.UserPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("TotalStorageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("total_storage_mb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UsedStorageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("used_storage_mb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_plans");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_plans_user_id");

                    b.ToTable("user_plans", (string)null);
                });

            modelBuilder.Entity("Orbit_BE.Entities.CanvasEdge", b =>
                {
                    b.HasOne("Orbit_BE.Entities.Node", "FromNode")
                        .WithMany()
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_canvas_edges_nodes_from_node_id");

                    b.HasOne("Orbit_BE.Entities.Node", "ToNode")
                        .WithMany()
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_canvas_edges_nodes_to_node_id");

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("Orbit_BE.Entities.Node", b =>
                {
                    b.HasOne("Orbit_BE.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nodes_nodes_parent_id");

                    b.HasOne("Orbit_BE.Entities.User", "User")
                        .WithMany("Nodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nodes_users_user_id");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Orbit_BE.Entities.NodeFile", b =>
                {
                    b.HasOne("Orbit_BE.Entities.Node", "Node")
                        .WithMany("Files")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_files_nodes_node_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Orbit_BE.Entities.NodePosition", b =>
                {
                    b.HasOne("Orbit_BE.Entities.Node", "Node")
                        .WithOne("Position")
                        .HasForeignKey("Orbit_BE.Entities.NodePosition", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_positions_nodes_node_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Orbit_BE.Entities.Payment", b =>
                {
                    b.HasOne("Orbit_BE.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");
                });

            modelBuilder.Entity("Orbit_BE.Entities.UserPlan", b =>
                {
                    b.HasOne("Orbit_BE.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_plans_users_user_id");
                });

            modelBuilder.Entity("Orbit_BE.Entities.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Orbit_BE.Entities.User", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
